#!/usr/bin/env python3
"""Build the offline 1–3 letter lexicon from the SCOWL 2020.12.07 archive."""
import argparse
from pathlib import Path
import re
import tarfile


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("archive", type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
words = {"a", "i"}
# SCOWL also lists alphabet symbols and their plurals as words. They are not
# standalone words for this activity. Ordinary as/is/us remain valid.
letter_plurals = {letter + "s" for letter in "bcdefghjklmnopqrtvwxyz"}
# A few unit/math abbreviations also occur in SCOWL's ordinary-word files.
abbreviations = {"aeq", "amu", "csc", "dkl", "gre", "hhd", "kb", "lm", "ln", "lx", "mb", "mf", "ss"}
with tarfile.open(args.archive) as archive:
    for member in archive.getmembers():
        match = re.search(r"/final/(english|american|british)-words\.(\d+)$", member.name)
        if not match or int(match[2]) > 80:
            continue
        for word in archive.extractfile(member).read().decode("latin1").splitlines():
            # Retain the established three-letter q word from the rarer tier.
            if int(match[2]) > 70 and word != "qat":
                continue
            if re.fullmatch("[a-z]{2,3}", word) and word not in letter_plurals | abbreviations:
                words.add(word)
    target = root / "assets/words"
    target.mkdir(parents=True, exist_ok=True)
    (target / "SCOWL-Copyright.txt").write_bytes(archive.extractfile("scowl-2020.12.07/Copyright").read())
    lines = ["# Generated by tools/build_short_word_list.py; see assets/words/README.md.",
             "class_name EnglishWords", "extends RefCounted", "", "const WORDS := {"]
    ordered = sorted(words)
    for start in range(0, len(ordered), 8):
        lines.append("\t" + " ".join(f'"{word}": true,' for word in ordered[start:start + 8]))
    lines += ["}", "", "", "static func is_word(letters: String) -> bool:",
              "\treturn WORDS.has(letters.to_lower())", ""]
    (target / "english_words.gd").write_text("\n".join(lines))
print(f"Bundled {len(words)} words, excluding proper-name/abbreviation lists and alphabet symbols.")
